name: Binance Alpha Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: [ main ]
    paths:
      - "alpha_alert.py"
      - "requirements.txt"
      - ".github/workflows/alpha-alert.yml"

concurrency:
  group: alpha-alert-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show alpha_alert.py head
        run: |
          echo "HEAD commit: $(git rev-parse HEAD)"
          sed -n '1,80p' alpha_alert.py
          echo "---- grep endpoints ----"
          grep -n "CMS_.*_API" alpha_alert.py || true

      - name: Run alpha_alert
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # 필요 시 엔드포인트를 환경변수로 강제 오버라이드 가능
          CMS_LIST_API: https://www.binance.com/bapi/apex/v1/public/apex/cms/article/list/query
          CMS_DETAIL_API: https://www.binance.com/bapi/apex/v1/public/apex/cms/article/detail/query
          PAGES: "1"
        run: |
          python alpha_alert.py

      - name: Persist seen_ids.json
        if: always()
        run: |
          if [ -f seen_ids.json ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add seen_ids.json
            git commit -m "chore: update seen_ids.json [skip ci]" || true
            git push || true
          else
            echo "seen_ids.json not found; nothing to commit."
          fi
