name: Alpha Alert

on:
  workflow_dispatch:         # 수동 실행 버튼
  schedule:
    - cron: "*/15 * * * *"   # 15분마다 (UTC 기준)

permissions:
  contents: write            # seen_ids.json 업데이트 푸시용

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run monitor (send only when new)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python alpha_alert.py

      - name: Commit seen_ids.json if changed
        run: |
          if [ -n "$(git status --porcelain seen_ids.json)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add seen_ids.json
            git commit -m "chore: update seen ids [skip ci]" || true
            git push
          else
            echo "No changes in seen_ids.json"
          fi
