name: Binance Alpha Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alpha_alert
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # 옵션: 페이지 더 보려면 조정(1~2면 충분)
          PAGES: "1"
        run: |
          python alpha_alert.py

      - name: Persist seen_ids.json
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_ids.json || true
          git commit -m "chore: update seen_ids.json [skip ci]" || true
          git push || true
