name: Binance Alpha Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다
  push:
    branches: [ main ]

concurrency:
  group: alpha-alert-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run alpha_alert
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # 새 글이 없어도 '없으면 없음!' 보내기 (원치 않으면 0)
          ALWAYS_NOTIFY_NO_RESULT: "1"
          NO_RESULT_MESSAGE: "없으면 없음! ✅ (새 상장 알림 없음)"
        run: |
          python alpha_alert.py

      - name: Persist local state
        if: always()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_ids.json .alpha_alert_initialized || true
          git commit -m "chore: update state [skip ci]" || true
          git push || true
