name: Alpha Alert
on:
  schedule:
    - cron: "*/15 * * * *"      # 15분마다 (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run (once)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ONCE: "1"
        run: python alpha_alert.py
      - name: Persist seen IDs
        run: |
          if [ -f seen_alpha_ids.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add seen_alpha_ids.json
            git commit -m "chore: update seen ids [skip ci]" || echo "No changes"
            git push || true
